node {
  stage('Checkout') {
    git branch: 'master', url: 'https://github.com/masshun/TaskManagement.git'
  }

  stage('Build') {
    dir('./Modules') {
      gradle('clean')
      gradle('compileTestGroovy')
    }
  }

  stage('UnitTest') {
    dir('./Modules') {
      gradle('test')
      junit '/build/test-results/**/TEST-*.xml'
    }
  }

  stage('IntegrationTest') {
    stage('CodeTableDownload') {
      dir('./SoapUi') {
        bat 'AutoRun.bat'
        junit '/results/**/*-JUNIT.xml'
      }
    }
  }
}

def gradle(command) {
  bat "./gradlew.bat $command"

}