CREATE DATABASE IF NOT EXISTS task_management;
USE task_management;


CREATE TABLE IF NOT EXISTS user (
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS task (
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id INT(11) NOT NULL,
	title VARCHAR(255) NOT NULL,
	content VARCHAR(255) NOT NULL,
	label VARCHAR(20) NOT NULL,
	user_addressee_id INT(11) NOT NULL,
	deadline DATETIME NOT NULL,
	status VARCHAR(10) NOT NULL -- '未完'・'進行中'・'完了' 
);